# postgres
#
defaults_development: &defaults_development
  adapter: postgresql
  encoding: unicode
  username: albert1
  password: 1234
  host: localhost

development:
  database: datab_1
  <<: *defaults_development

test:
  database: datab_2
  <<: *defaults_development
