# postgres
#
defaults_development: &defaults_development
  adapter: postgresql
  encoding: unicode
  username: app_name
  password: 1234
  host: localhost

development:
  database: l
  <<: *defaults_development

test:
  database: m
  <<: *defaults_development
